---
- name: Check Apache status on localhost
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if Apache (httpd) service is present
      ansible.builtin.debug:
        msg: >
          {% if 'httpd.service' in ansible_facts.services %}
            Apache service is installed.
          {% else %}
            Apache service NOT found.
          {% endif %}

    - name: Show Apache service status
      ansible.builtin.debug:
        msg: >
          {% if 'httpd.service' in ansible_facts.services %}
            Status: {{ ansible_facts.services['httpd.service'].state }}
          {% else %}
            No Apache service found to check status.
          {% endif %}
