- name: Remediate Windows Server 2022 CIS compliance
  hosts: windows
  gather_facts: yes

  roles:
    - role: ansible-lockdown.windows_2022_cis

  post_tasks:
    - name: Confirm GPO backups exist on Windows
      win_command: dir C:\GPOBackups


# Remediation control
win22cis_ansible_remediation: true           # Enable remediation directly on Windows hosts
win22cis_create_gpos: false                  # Disable GPO creation
win22cis_backup_custom_gpos: true            # Enable backup of GPOs
win22cis_backup_location_style: Windows      # Store backup on Windows host

# Enable specific CIS sections
win22cis_section01: true    # Account Policies
win22cis_section02: true    # Local Policies
win22cis_section05: true    # System Services
win22cis_section09: true    # Windows Firewall
win22cis_section17: true    # Advanced Audit Policy
win22cis_section18: true    # Admin Templates - Computer
win22cis_section19: true    # Admin Templates - User

# Control reboot and skip flags
skip_reboot: false
win_skip_for_test: false

# Example individual rule overrides (set false to skip)
win22cis_rule_2_2_26: false
win22cis_rule_2_2_27: false















