# Do NOT remediate yet
win22cis_ansible_remediation: false

# Do NOT create new CIS GPOs
win22cis_create_gpos: false

# Enable backup of existing GPOs
win22cis_backup_custom_gpos: true
win22cis_backup_location_style: Windows   # keep backups on Windows, fetch later

# Enable audit-only mode (results go to Ansible output, not JSON files)
win22cis_run_audit: true
win22cis_audit_only: true





- name: Backup GPOs and Audit Windows Server 2022 CIS compliance
  hosts: windows
  gather_facts: yes

  roles:
    - role: ansible-lockdown.windows_2022_cis
      vars:
        # Backup only (no remediation)
        win22cis_backup_custom_gpos: true
        win22cis_create_gpos: false
        win22cis_ansible_remediation: false
        win22cis_backup_location_style: Windows

        # Enable audit mode (console only)
        win22cis_run_audit: true
        win22cis_audit_only: true

  post_tasks:
    - name: Fetch GPO backups
      fetch:
        src: C:\GPOBackups
        dest: manifests/gpo-backups
        flat: no












