---
- name: Check Apache (httpd) status on RHEL localhost
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if Apache (httpd) service is installed
      when: "'httpd.service' in ansible_facts.services"
      debug:
        msg: "Apache is {{ ansible_facts.services['httpd.service'].state }}"

    - name: Apache not found
      when: "'httpd.service' not in ansible_facts.services"
      debug:
        msg: "Apache (httpd) is not installed on this host."
