- name: Validate Windows Server 2022 CIS compliance
  hosts: windows
  gather_facts: yes

  vars_files:
    - group_vars/windows.yml   # your CIS manifest file

  roles:
    - role: ansible-lockdown.windows_2022_cis
      vars:
        win22cis_ansible_remediation: false   # validation only
        win22cis_create_gpos: false           # no GPOs yet

  post_tasks:
    - name: Fetch validation report
      fetch:
        src: C:\CIS\cis_validation_report.json
        dest: manifests/pre-check/cis_validation_report.json
        flat: yes






