---
- name: Diagnose service facts
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Print all service facts
      debug:
        var: ansible_facts.services

