---
- name: Test playbook inside container
  hosts: localhost
  gather_facts: yes
  become: no

  tasks:
    - name: Show OS details
      debug:
        msg: "Operating System: {{ ansible_facts['os_family'] }} {{ ansible_facts['distribution_version'] }}"

    - name: Show running processes (first 10)
      command: ps aux --sort=-%mem
      register: ps_output

    - name: Display first 10 processes
      debug:
        var: ps_output.stdout_lines[:10]

    - name: Show environment variables
      command: env
      register: env_output

    - name: Display environment variables
      debug:
        var: env_output.stdout_lines



