---
- name: Minimal container test playbook
  hosts: localhost
  gather_facts: yes
  become: no

  tasks:
    - name: Show OS details
      debug:
        msg: "OS: {{ ansible_facts['os_family'] }} {{ ansible_facts['distribution_version'] }}"






